pipeline {
    agent any

    stages {
        stage('Install MySQL Server') {
            steps {
                sshagent(['id_rsa']) {
                    sh '''
                    ssh test@192.168.56.14 "sudo apt-get update && sudo apt-get install mysql-server mysql-client -y"
                    '''
                }
            }
        }
        stage('Create WordPress Database and User') {
            steps {
                sshagent(['id_rsa']) {
                    sh '''
                    ssh test@192.168.56.14 "sudo mysql -e << EOF 
                    CREATE DATABASE IF NOT EXISTS wordpress;
                    CREATE USER 'new_user'@'localhost' IDENTIFIED BY 'Password@12';
                    GRANT ALL PRIVILEGES ON wordpress.* TO 'new_user'@'localhost';
                    FLUSH PRIVILEGES;
                    EOF
                    "
                    '''
                }
            }
        }
    }
}


                    ssh test@192.168.56.14 "sudo mysql -e 'CREATE DATABASE IF NOT EXISTS wordpress;'"
                    ssh test@192.168.56.14 "sudo mysql -e 'CREATE USER 'new_user'@'localhost' IDENTIFIED BY 'Password@12';'"