pipeline {
    agent any

    environment {
        DB_NAME = 'wordpress'
        DB_USER = 'wp_user'
        DB_PASSWORD = 'Password#1'
    }

    stages {
        stage('Install MySQL Server') {
            steps {
                sshagent(['id_rsa']) {
                    sh '''
                    ssh test@192.168.56.14 "sudo apt-get update && sudo apt-get install mysql-server mysql-client -y"
                    '''
                }
            }
        }
        stage('Create WordPress Database and User') {
            steps {
                sshagent(['id_rsa']) {
                    sh """
                    ssh test@192.168.56.14 "sudo mysql <<EOF
                        CREATE DATABASE IF NOT EXISTS ${env.DB_NAME};
                        CREATE USER IF NOT EXISTS '${env.DB_USER}'@'localhost' IDENTIFIED BY '${env.DB_PASSWORD}';
                        CREATE USER IF NOT EXISTS '${env.DB_USER}'@'192.168.56.12' IDENTIFIED BY '${env.DB_PASSWORD}';
                        CREATE USER IF NOT EXISTS '${env.DB_USER}'@'192.168.56.13' IDENTIFIED BY '${env.DB_PASSWORD}';
                        ALTER USER '${env.DB_USER}'@'localhost' IDENTIFIED WITH caching_sha2_password BY '${env.DB_PASSWORD}';
                        ALTER USER '${env.DB_USER}'@'192.168.56.12' IDENTIFIED WITH caching_sha2_password BY '${env.DB_PASSWORD}';
                        ALTER USER '${env.DB_USER}'@'192.168.56.13' IDENTIFIED WITH caching_sha2_password BY '${env.DB_PASSWORD}';
                        GRANT ALL PRIVILEGES ON ${env.DB_NAME}.* TO '${env.DB_USER}'@'localhost';
                        GRANT ALL PRIVILEGES ON ${env.DB_NAME}.* TO '${env.DB_USER}'@'192.168.56.12';
                        GRANT ALL PRIVILEGES ON ${env.DB_NAME}.* TO '${env.DB_USER}'@'192.168.56.13';
                        FLUSH PRIVILEGES;
EOF
                    "
                    """
                }
            }
        }
        stage('Update MySQL Configuration') {
            steps {
                sshagent(['id_rsa']) {
                    sh """
                    ssh test@192.168.56.14 "sudo sed -i 's/bind-address[[:space:]]*=.*/bind-address    = 0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf"
                    """
                }
            }
        }
        stage('Restart MySQL Service') {
            steps {
                sshagent(['id_rsa']) {
                    sh '''
                    ssh test@192.168.56.14 "sudo systemctl restart mysql"
                    ssh test@192.168.56.14 "sudo systemctl status mysql"
                    '''
                }
            }
        }   
    }
}
