pipeline {
    agent any

    stages {
        stage('Install Nginx on Load Balancer Server') {
            steps {
                sshagent(['id_rsa']) {
                    sh '''
                    ssh test@192.168.56.11 "sudo apt-get update && sudo apt-get install nginx -y"
                    '''
                }
            }
        }
        stage('Configure Nginx as Load Balancer') {
            steps {
                sshagent(['id_rsa']) {
                    sh '''
                    ssh test@192.168.56.11 "sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
                    upstream wordpress_backend {
                        server 192.168.56.12;
                        server 192.168.56.13;
                    }
                    
                    server {
                        listen 80 default_server;
                        listen [::]:80 default_server;
                        
                        location / {
                            proxy_pass http://wordpress_backend;
                        }
                    }
                    '"
                    '''
                }
            }
        }
        
        stage('Restart Nginx') {
            steps {
                sshagent(['id_rsa']) {
                    sh '''
                    ssh test@192.168.56.11 "sudo systemctl restart nginx"
                    ssh test@192.168.56.11 "sudo systemctl status nginx"
                    ssh test@192.168.56.11 "sudo systemctl status nginx"
                    '''
                }
            }
        }
    }
}
