pipeline {
    agent any
    stages {
        stage('Build') {
            parallel {
                stage('MySQL') {
                    steps {
                        script {
                            checkout scm
                            dir('apps/mysql') {
                                // Se rulează fișierul Jenkinsfile pentru aplicația MySQL
                                load 'Jenkinsfile'
                            }
                        }
                    }
                }
                stage('Nginx') {
                    steps {
                        script {
                            checkout scm
                            dir('apps/nginx') {
                                // Se rulează fișierul Jenkinsfile pentru aplicația Nginx
                                load 'Jenkinsfile'
                            }
                        }
                    }
                }
                stage('Wordpress') {
                    steps {
                        script {
                            checkout scm
                            dir('apps/wordpress') {
                                // Se rulează fișierul Jenkinsfile pentru aplicația Wordpress
                                load 'Jenkinsfile'
                            }
                        }
                    }
                }
            }
        }
    }
}
